### ISSUE TITLE
Register the package

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/GameTheory.jl#138]
https://github.com/JuliaRegistries/Registrator.jl

**Comment by oyamad** [comment]
@JuliaRegistrator register()

**Comment by sglyon** [comment]
Hey @oyamad I tried to register this package and it wasn't accepted becuase the name is too general https://github.com/JuliaRegistries/General/pull/44864

Perhaps we could rename to something like `GameTheory.jl`?

**Comment by oyamad** [comment]
@sglyon Sorry I haven't responded.

The reaction from JuliaRegistries is understandable.
Renaming causes a bit of costs. The question is: is registration worth the costs? My evaluation at the [last time](https://github.com/JuliaRegistries/General/pull/38768) was that the net benefit from registration was negative.

I would like to let you decide this time. Thanks!

**Comment by sglyon** [comment]
Thanks @oyamad I am teaching a course right now using Pluto.jl notebooks. In that environment I can't use non-registered packages (at least not easily!)

So I've gone ahead and changed the name.

I have also updated the notebooks refereed to the documentation (in other QuantEcon repositories) to use the new package name. I will push those changes soon

**Comment by sglyon** [comment]
oh no! I'm sorry about that!

I chose to do the in place rename to keep the repo issues/pull requests/CI config all setup.

Thanks for being understanding.
